# Generated by Django 4.2.1 on 2023-07-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_submission_feedback_submission_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='started_test',
            field=models.BooleanField(default=False),
        ),
    ]
