# Generated by Django 4.2.1 on 2023-07-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_enrollment_progress_enrollment_started_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.lesson'),
            preserve_default=False,
        ),
    ]
