# Generated by Django 4.2.1 on 2023-07-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0008_remove_choice_question_remove_submission_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='passing_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='passing_score',
            field=models.FloatField(default=0),
        ),
    ]
