# Generated by Django 4.2.1 on 2023-07-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0009_course_passing_score_lesson_passing_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='onlinecourse.course'),
            preserve_default=False,
        ),
    ]
