# Generated by Django 4.2.1 on 2023-07-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0011_submission_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='lesson',
        ),
    ]
