# Generated by Django 4.2.1 on 2023-07-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0013_submission_final_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='final_grade',
            field=models.FloatField(default=0),
        ),
    ]
