# Generated by Django 4.2.1 on 2023-07-21 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0014_alter_submission_final_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.lesson'),
        ),
    ]
