# Generated by Django 4.2.1 on 2023-07-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0015_alter_enrollment_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.lesson'),
            preserve_default=False,
        ),
    ]
